/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectmanagementsystem;
import static projectmanagementsystem.Connection.getConnection;
import static projectmanagementsystem.Query.getSelectResult;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import static projectmanagementsystem.Connection.getConnection;
import static projectmanagementsystem.Query.getSelectResult;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.JDBCType;
import static java.sql.JDBCType.NULL;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author prank
 */
public class LoginPage extends javax.swing.JFrame {

    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    /**
     * Creates new form Login
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtFieldUsername = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jComboBox = new javax.swing.JComboBox<>();
        jBtnSubmit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Username:");

        jLabel2.setText("Password:");

        jTxtFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFieldUsernameActionPerformed(evt);
            }
        });

        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose an Option", "Student", "Teacher", "Group" }));
        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });

        jBtnSubmit.setText("Login");
        jBtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSubmitActionPerformed(evt);
            }
        });

        jLabel3.setText("Type:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnSubmit)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                        .addComponent(jTxtFieldUsername))
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(39, 39, 39)
                .addComponent(jBtnSubmit)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFieldUsernameActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void jBtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSubmitActionPerformed
            checkAuth(); 
            // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSubmitActionPerformed

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxActionPerformed

    private void jPasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {                                          
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                checkAuth();
        }
    }                                         

    private void jTxtFieldUsernameKeyPressed(java.awt.event.KeyEvent evt) {                                             
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                checkAuth();
       }
    }             
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }
    
    public void checkAuth()
    {
            String username = jTxtFieldUsername.getText();
            String password = new String(jPasswordField.getPassword());
            String choice = jComboBox.getSelectedItem().toString();
            if(username.length() == 0  || password.length() == 0){
                JOptionPane.showMessageDialog(null, "Username and Password cannot be blank.", "Login Error", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                try 
                {
                    System.out.println("hi");
                    if(choice.equals("Group"))
                    {   
                        String query = "SELECT * FROM Groups where username='"+username+"' && password='"+password+"'";
                        //java.sql.Connection con = getConnection();
                        Class.forName("com.mysql.jdbc.Driver");
                        con = DriverManager.getConnection("jdbc:mysql://localhost/ProjectManagementSystem","root","bubu");   
                        pst=con.prepareStatement(query);
                        ResultSet rs = pst.executeQuery(query);
                       // ResultSet rs = getSelectResult(query, con);
                       //System.out.println("hello");
                       //JOptionPane.showMessageDialog(this, "Hello");
                        if(rs.next()){
                            String fullName = rs.getString("username");
                            System.out.println("check");
                           // close();
                           this.setVisible(false);
                           Group g=new Group(jTxtFieldUsername.getText());
                            g.setVisible(true);
                            JOptionPane.showMessageDialog(null, "Welcome back "+ fullName, "Logged in Successfully", JOptionPane.INFORMATION_MESSAGE);
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "Login Error", "Error", JOptionPane.INFORMATION_MESSAGE); 
                        }
                    }
                    else if(choice.equals("Student"))
                    {
                        String query = "SELECT * FROM Students where username='"+username+"' && password='"+password+"'";
                        //java.sql.Connection con = getConnection();
                        Class.forName("com.mysql.jdbc.Driver");
                        con = DriverManager.getConnection("jdbc:mysql://localhost/ProjectManagementSystem","root","bubu");   
                        pst=con.prepareStatement(query);
                        ResultSet rs = pst.executeQuery(query);
                       // ResultSet rs = getSelectResult(query, con);
                       //System.out.println("hello");
                       //JOptionPane.showMessageDialog(this, "Hello");
                        if(rs.next()){
                            String fullName = rs.getString("username");
                            System.out.println("check");
                           // close();
                           this.setVisible(false);
                           Student s=new Student(jTxtFieldUsername.getText());
                            s.setVisible(true);
                            JOptionPane.showMessageDialog(null, "Welcome back "+ fullName, "Logged in Successfully", JOptionPane.INFORMATION_MESSAGE);
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "Login Error", "Error", JOptionPane.INFORMATION_MESSAGE); 
                        }
                    }
                    else
                    {
                         String query = "SELECT * FROM Teachers where username='"+username+"' && password='"+password+"'";
                        //java.sql.Connection con = getConnection();
                        Class.forName("com.mysql.jdbc.Driver");
                        con = DriverManager.getConnection("jdbc:mysql://localhost/ProjectManagementSystem","root","bubu");   
                        pst=con.prepareStatement(query);
                        ResultSet rs = pst.executeQuery(query);
                       // ResultSet rs = getSelectResult(query, con);
                       //System.out.println("hello");
                       //JOptionPane.showMessageDialog(this, "Hello");
                        if(rs.next()){
                            String fullName = rs.getString("username");
                            System.out.println("check");
                           // close();
                           this.setVisible(false);
                           Teacher t=new Teacher(jTxtFieldUsername.getText());
                            t.setVisible(true);
                            JOptionPane.showMessageDialog(null, "Welcome back "+ fullName, "Logged in Successfully", JOptionPane.INFORMATION_MESSAGE);
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "Login Error", "Error", JOptionPane.INFORMATION_MESSAGE); 
                        }
                    }

                    con.close();
                }
                catch(Exception e)
                {
                   System.out.println(e.getMessage());
                }

            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSubmit;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTxtFieldUsername;
    // End of variables declaration//GEN-END:variables
}
